import { Drill } from '../types/game';

export const DRILLS: { [id: string]: Drill } = {
  rusty_drill: {
    id: 'rusty_drill',
    name: 'Rusty Drill',
    description: 'A basic, reliable drill. Nothing fancy.',
    icon: '🪛',
    basePower: 20,
    cooldownMs: 300,
    fuelConsumption: 0.5,
    price: { dirt: 0 }, // Free / Default
  },
  stone_drill: {
    id: 'stone_drill',
    name: 'Stone Drill',
    description: 'A sturdy drill made of reinforced rock.',
    icon: '🪨',
    basePower: 60,
    cooldownMs: 400,
    fuelConsumption: 0.6,
    price: { stone: 50 },
  },
  iron_drill: {
    id: 'iron_drill',
    name: 'Iron Drill',
    description: 'Sharpened iron tip for consistent power.',
    icon: '🥈',
    basePower: 150,
    cooldownMs: 500,
    fuelConsumption: 0.8,
    price: { iron: 100, coal: 50 },
  },
  gold_drill: {
    id: 'gold_drill',
    name: 'Gold Drill',
    description: 'High-speed drilling with high fuel cost.',
    icon: '🟡',
    basePower: 400,
    cooldownMs: 600,
    fuelConsumption: 1.5,
    price: { gold: 100, iron: 50 },
  },
  diamond_drill: {
    id: 'diamond_drill',
    name: 'Diamond Drill',
    description: 'The ultimate drill. Pierces anything.',
    icon: '💎',
    basePower: 1000,
    cooldownMs: 800,
    fuelConsumption: 1.0,
    price: { diamond: 50, gold: 100 },
  },
  coal_drill: {
    id: 'coal_drill',
    name: 'Coal Drill',
    description: 'Uses coal thermal energy. Efficient but crude.',
    icon: '🔥',
    basePower: 600,
    cooldownMs: 700,
    fuelConsumption: 0.5,
    price: { coal: 300, iron: 50 },
  },
};
