// [자동 생성됨] 이 파일은 scripts/generateAtlasMap.js 스크립트에 의해 생성되었습니다.
// 에셋이 추가되면 이 파일이 자동으로 업데이트됩니다.

export const ATLAS_FILE_MAPPING = {
  AttackRune: 'AttackRune.png',
  BaseTileset: 'BaseTileset.png',
  BookIcon: 'BookIcon.webp',
  BossCoreTile: 'boss_core.png',
  BossSkinTile: 'boss_skin.png',
  CrimsonStoneIcon: 'CrimsonStoneIcon.png',
  CrimsonStoneTile: 'CrimsonStoneTile.png',
  CritDmgRune: 'CritDmgRune.png',
  CritRateRune: 'CritRateRune.png',
  DiamondDrill: 'DiamondDrill.png',
  DirtTile: 'DirtTile.png',
  EmeraldDrill: 'EmeralDrill.png',
  FervorStoneIcon: 'FervorStoneIcon.png',
  FervorStoneTile: 'FervorStoneTile.png',
  GaleBat: 'GaleBat.png',
  GaleStoneIcon: 'GaleStoneIcon.png',
  GaleStoneTile: 'GaleStoneTile.png',
  GoldDrill: 'GoldDrill.png',
  GoldIcon: 'MoneyIcon.webp',
  InventoryIcon: 'InventoryIcon.webp',
  IronDrill: 'IronDrill.png',
  LuckRune: 'LuckRune.png',
  LustfulWhisperer: 'LustfulWhisperer.png',
  Mechanic: 'Mechanic.png',
  Merchant: 'Merchant.png',
  MiningSpeedRune: 'MiningSpeedRune.png',
  MoveSpeedRune: 'MoveSpeedRune.png',
  Player: 'Player.png',
  Refinery: 'Refinery.png',
  RustyDrill: 'RustyDrill.png',
  SettingsIcon: 'SettingsIcon.webp',
  StatusIcon: 'StatusIcon.webp',
  StoneDrill: 'StoneDrill.png',
  StoneTile: 'StoneTile.png',
  WindTornSoul: 'WindTornSoul.png',
} as const;

export type AtlasIconName = keyof typeof ATLAS_FILE_MAPPING;
