// [자동 생성됨] 이 파일은 scripts/generateAtlasMap.js 스크립트에 의해 생성되었습니다.
// 에셋이 추가되면 이 파일이 자동으로 업데이트됩니다.

export const ATLAS_FILE_MAPPING = {
  attack_rune: 'AttackRune.png',
  base_tileset: 'BaseTileset.png',
  book: 'BookIcon.webp',
  boss_core: 'boss_core.png',
  boss_skin: 'boss_skin.png',
  coal_icon: 'CoalIcon.png',
  coal_tile: 'coal.png',
  crit_dmg_rune: 'CritDmgRune.png',
  crit_rate_rune: 'CritRateRune.png',
  diamond_drill: 'DiamondDrill.png',
  diamond_icon: 'DiamondIcon.png',
  diamond_tile: 'diamond.png',
  dirt_icon: 'DirtIcon.png',
  dirt_tile: 'dirt.png',
  dungeon_bricks_tile: 'dungeon_bricks.png',
  emerald_drill: 'EmeralDrill.png',
  emerald_icon: 'EmeraldIcon.png',
  emerald_tile: 'emerald.png',
  gold: 'MoneyIcon.webp',
  gold_drill: 'GoldDrill.png',
  gold_icon: 'GoldIcon.png',
  gold_tile: 'gold.png',
  inventory: 'InventoryIcon.webp',
  iron_drill: 'IronDrill.png',
  iron_icon: 'IronIcon.png',
  iron_tile: 'iron.png',
  luck_rune: 'LuckRune.png',
  mechanic: 'Mechanic.png',
  merchant: 'Merchant.png',
  move_rune: 'MoveSpeedRune.png',
  obsidian_tile: 'obsidian.png',
  oros_face: 'OrosFace.png',
  pebble_golem: 'PebbleGolem.png',
  player: 'Player.png',
  refinery: 'Refinery.png',
  ruby_icon: 'RubyIcon.png',
  ruby_tile: 'ruby.png',
  rusty_drill: 'RustyDrill.png',
  sapphire_icon: 'SapphireIcon.png',
  sapphire_tile: 'sapphire.png',
  settings: 'SettingsIcon.webp',
  speed_rune: 'MiningSpeedRune.png',
  status: 'StatusIcon.webp',
  steel_scale_turtle: 'SteelScaleTurtle.png',
  stone_drill: 'StoneDrill.png',
  stone_icon: 'StoneIcon.png',
  stone_tile: 'stone.png',
  thief_mole: 'ThiefMole.png',
  uranium_tile: 'uranium.png',
  wall_tile: 'wall.png',
} as const;

export type AtlasIconName = keyof typeof ATLAS_FILE_MAPPING;
