import { Drill } from '../types/game';
import { AtlasIconName } from './atlasMap';

/**
 * 게임 내 드릴 및 곡괭이 장비 데이터를 정의합니다.
 * 각 장비는 특정 서클의 광물을 사용하여 제작할 수 있습니다.
 */
export const DRILLS: { [id: string]: Drill } = {
  rusty_drill: {
    id: 'rusty_drill',
    name: 'Rusty Drill',
    description: 'A basic drill.',
    icon: '🪛',
    equipmentType: 'drill',
    basePower: 20,
    cooldownMs: 200,
    moveSpeedMult: 1.0,
    price: { goldCoins: 0 },
    image: 'rusty_drill',
    maxSkillSlots: 3,
  },
  rusty_pickaxe: {
    id: 'rusty_pickaxe',
    name: 'Rusty Pickaxe',
    description: 'Slow attack speed, but packs a heavy punch.',
    icon: '⛏️',
    equipmentType: 'pickaxe',
    basePower: 55,
    cooldownMs: 500,
    moveSpeedMult: 1.0,
    price: { goldCoins: 100 },
    maxSkillSlots: 3,
  },
  stone_drill: {
    id: 'stone_drill',
    name: 'Stone Drill',
    description: 'A sturdy drill made of crimsonstone.',
    icon: '🪨',
    equipmentType: 'drill',
    basePower: 85,
    cooldownMs: 180,
    moveSpeedMult: 1.0,
    price: { crimsonstone: 25 },
    image: 'stone_drill',
    maxSkillSlots: 3,
  },
  stone_pickaxe: {
    id: 'stone_pickaxe',
    name: 'Stone Pickaxe',
    description: 'A heavy pickaxe that can shatter lustrous rocks.',
    icon: '⚒️',
    equipmentType: 'pickaxe',
    basePower: 150,
    cooldownMs: 450,
    moveSpeedMult: 1.0,
    price: { crimsonstone: 40 },
    maxSkillSlots: 3,
  },
  iron_drill: {
    id: 'iron_drill',
    name: 'Gale Drill',
    description: 'Uses whirlwind-infused ores for faster rotation.',
    icon: '🥈',
    equipmentType: 'drill',
    basePower: 220,
    cooldownMs: 170,
    moveSpeedMult: 1.0,
    price: { galestone: 50, crimsonstone: 30 },
    image: 'iron_drill',
    maxSkillSlots: 3,
  },
  iron_pickaxe: {
    id: 'iron_pickaxe',
    name: 'Gale Pickaxe',
    description: 'A pickaxe that swings with the speed of a storm.',
    icon: '🪓',
    equipmentType: 'pickaxe',
    basePower: 380,
    cooldownMs: 400,
    moveSpeedMult: 1.0,
    price: { galestone: 75, crimsonstone: 45 },
    maxSkillSlots: 3,
  },
  gold_drill: {
    id: 'gold_drill',
    name: 'Fervor Drill',
    description: 'Heated by passion, this drill never stops.',
    icon: '🥇',
    equipmentType: 'drill',
    basePower: 450,
    cooldownMs: 160,
    moveSpeedMult: 1.0,
    price: { fervorstone: 60, galestone: 40 },
    image: 'gold_drill',
    maxSkillSlots: 3,
  },
  gold_pickaxe: {
    id: 'gold_pickaxe',
    name: 'Fervor Pickaxe',
    description: 'Strikes with the heat of a thousand desires.',
    icon: '🔱',
    equipmentType: 'pickaxe',
    basePower: 750,
    cooldownMs: 380,
    moveSpeedMult: 1.0,
    price: { fervorstone: 100, galestone: 60 },
    maxSkillSlots: 3,
  },
  diamond_drill: {
    id: 'diamond_drill',
    name: 'Gluttony Drill',
    description: 'Consumes the earth as it descends into the rot.',
    icon: '💎',
    equipmentType: 'drill',
    basePower: 900,
    cooldownMs: 140,
    moveSpeedMult: 1.0,
    price: { moldstone: 100, fervorstone: 50 },
    image: 'diamond_drill',
    maxSkillSlots: 3,
  },
  diamond_pickaxe: {
    id: 'diamond_pickaxe',
    name: 'Gluttony Pickaxe',
    description: 'A heavy tool forged to break through the silt.',
    icon: '💠',
    equipmentType: 'pickaxe',
    basePower: 1600,
    cooldownMs: 350,
    moveSpeedMult: 1.1,
    price: { siltstone: 60, moldstone: 80 },
    maxSkillSlots: 3,
  },
  emerald_drill: {
    id: 'emerald_drill',
    name: 'Gore Drill',
    description: 'A drill drenched in the essence of gluttony.',
    icon: '💚',
    equipmentType: 'drill',
    basePower: 2100,
    cooldownMs: 135,
    moveSpeedMult: 1.1,
    specialEffect: 'efficient',
    price: { gorestone: 120, siltstone: 80 },
    image: 'emerald_drill',
    maxSkillSlots: 3,
  },
  emerald_pickaxe: {
    id: 'emerald_pickaxe',
    name: 'Gore Pickaxe',
    description: 'Splits open the earth like raw flesh.',
    icon: '🍀',
    equipmentType: 'pickaxe',
    basePower: 3500,
    cooldownMs: 320,
    moveSpeedMult: 1.1,
    price: { gorestone: 180, siltstone: 100 },
    maxSkillSlots: 3,
  },
  ruby_drill: {
    id: 'ruby_drill',
    name: 'Greed Drill',
    description: 'Forged from the first gold found in the hoarding pits.',
    icon: '❤️',
    equipmentType: 'drill',
    basePower: 4800,
    cooldownMs: 130,
    moveSpeedMult: 1.1,
    price: { goldstone: 150, gorestone: 100 },
    maxSkillSlots: 4,
  },
  ruby_pickaxe: {
    id: 'ruby_pickaxe',
    name: 'Greed Pickaxe',
    description: 'A pickaxe for those who desire everything.',
    icon: '🏮',
    equipmentType: 'pickaxe',
    basePower: 8500,
    cooldownMs: 300,
    moveSpeedMult: 1.1,
    price: { luststone: 120, goldstone: 150 },
    maxSkillSlots: 4,
  },
  sapphire_drill: {
    id: 'sapphire_drill',
    name: 'Midas Drill',
    description: 'Turns the very stone into progress.',
    icon: '💙',
    equipmentType: 'drill',
    basePower: 12000,
    cooldownMs: 125,
    moveSpeedMult: 1.2,
    price: { midasite: 150, luststone: 100 },
    maxSkillSlots: 4,
  },
  sapphire_pickaxe: {
    id: 'sapphire_pickaxe',
    name: 'Midas Pickaxe',
    description: 'The ultimate tool of the fourth circle.',
    icon: '🧿',
    equipmentType: 'pickaxe',
    basePower: 22000,
    cooldownMs: 280,
    moveSpeedMult: 1.2,
    price: { midasite: 200, goldstone: 300 },
    maxSkillSlots: 4,
  },
  uranium_drill: {
    id: 'uranium_drill',
    name: 'Wrathful Drill',
    description: 'Vibrates with the uncontrollable rage of the abyss.',
    icon: '☢️',
    equipmentType: 'drill',
    basePower: 35000,
    cooldownMs: 120,
    moveSpeedMult: 1.2,
    specialEffect: 'explosive',
    price: { ragestone: 200, cinderstone: 300 },
    maxSkillSlots: 5,
  },
  uranium_pickaxe: {
    id: 'uranium_pickaxe',
    name: 'Wrathful Pickaxe',
    description: 'Every strike is a volcanic eruption.',
    icon: '☣️',
    equipmentType: 'pickaxe',
    basePower: 65000,
    cooldownMs: 260,
    moveSpeedMult: 1.2,
    price: { furystone: 150, ragestone: 400 },
    maxSkillSlots: 5,
  },
  obsidian_drill: {
    id: 'obsidian_drill',
    name: 'Abyssal Dreadnought',
    description: 'A drill that has seen the bottom of the world.',
    icon: '🖤',
    equipmentType: 'drill',
    basePower: 150000,
    cooldownMs: 110,
    moveSpeedMult: 1.3,
    price: { abyssstone: 500, goldCoins: 1000000 },
    maxSkillSlots: 6,
  },
  obsidian_pickaxe: {
    id: 'obsidian_pickaxe',
    name: 'Abyssal Breaker',
    description: 'The final tool for the final circle.',
    icon: '🌑',
    equipmentType: 'pickaxe',
    basePower: 300000,
    cooldownMs: 240,
    moveSpeedMult: 1.3,
    price: { abyssstone: 800, goldCoins: 2000000 },
    maxSkillSlots: 6,
  },
};

export const getDrillData = (id: string): Drill | undefined => {
  return DRILLS[id];
};
