import { Drill } from '../types/game';
import { AtlasIconName } from './atlasMap';

export const DRILLS: { [id: string]: Drill } = {
  rusty_drill: {
    id: 'rusty_drill',
    name: 'Rusty Drill',
    description: 'A basic drill.',
    icon: '🪛',
    equipmentType: 'drill',
    basePower: 20,
    cooldownMs: 200,
    moveSpeedMult: 1.0,
    price: { dirt: 0 },
    image: 'rusty_drill',
    maxSkillSlots: 3,
  },
  rusty_pickaxe: {
    id: 'rusty_pickaxe',
    name: 'Rusty Pickaxe',
    description: 'Slow attack speed, but packs a heavy punch.',
    icon: '⛏️',
    equipmentType: 'pickaxe',
    basePower: 55,
    cooldownMs: 500,
    moveSpeedMult: 1.0,
    price: { dirt: 5 },
    maxSkillSlots: 3,
  },
  stone_drill: {
    id: 'stone_drill',
    name: 'Stone Drill',
    description: 'A sturdy drill made of stone.',
    icon: '🪨',
    equipmentType: 'drill',
    basePower: 55,
    cooldownMs: 180,
    moveSpeedMult: 1.0,
    price: { stone: 25 },
    image: 'stone_drill',
    maxSkillSlots: 3,
  },
  stone_pickaxe: {
    id: 'stone_pickaxe',
    name: 'Stone Pickaxe',
    description: 'A heavy pickaxe that can shatter hard rocks in one go.',
    icon: '⚒️',
    equipmentType: 'pickaxe',
    basePower: 100,
    cooldownMs: 450,
    moveSpeedMult: 1.0,
    price: { stone: 40 },
    maxSkillSlots: 3,
  },
  iron_drill: {
    id: 'iron_drill',
    name: 'Iron Drill',
    description: 'Uses a sharp iron tip for consistent power.',
    icon: '🥈',
    equipmentType: 'drill',
    basePower: 100,
    cooldownMs: 170,
    moveSpeedMult: 1.0,
    price: { iron: 30, coal: 50 },
    image: 'iron_drill',
    maxSkillSlots: 3,
  },
  iron_pickaxe: {
    id: 'iron_pickaxe',
    name: 'Iron Pickaxe',
    description: 'An iron pickaxe with a powerful impact.',
    icon: '🪓',
    equipmentType: 'pickaxe',
    basePower: 180,
    cooldownMs: 400,
    moveSpeedMult: 1.0,
    price: { iron: 45, coal: 60 },
    maxSkillSlots: 3,
  },
  gold_drill: {
    id: 'gold_drill',
    name: 'Gold Drill',
    description: 'Shiny, but as hard as rock.',
    icon: '🥇',
    equipmentType: 'drill',
    basePower: 180,
    cooldownMs: 160,
    moveSpeedMult: 1.0,
    price: { gold: 30, iron: 50 },
    image: 'gold_drill',
    maxSkillSlots: 3,
  },
  gold_pickaxe: {
    id: 'gold_pickaxe',
    name: 'Gold Pickaxe',
    description: 'A symbol of wealth with formidable destructive power.',
    icon: '🔱',
    equipmentType: 'pickaxe',
    basePower: 300,
    cooldownMs: 380,
    moveSpeedMult: 1.0,
    price: { gold: 40, iron: 60 },
    maxSkillSlots: 3,
  },
  diamond_drill: {
    id: 'diamond_drill',
    name: 'Diamond Drill',
    description: 'Uses industrial-grade diamond for early depth.',
    icon: '💎',
    equipmentType: 'drill',
    basePower: 300,
    cooldownMs: 140,
    moveSpeedMult: 1.0,
    price: { diamond: 45, gold: 75 },
    image: 'diamond_drill',
    maxSkillSlots: 3,
  },
  diamond_pickaxe: {
    id: 'diamond_pickaxe',
    name: 'Diamond Pickaxe',
    description: 'A pickaxe carved from early-found diamonds.',
    icon: '💠',
    equipmentType: 'pickaxe',
    basePower: 450,
    cooldownMs: 350,
    moveSpeedMult: 1.0,
    price: { diamond: 60, gold: 75 },
    maxSkillSlots: 3,
  },
  emerald_drill: {
    id: 'emerald_drill',
    name: 'Emerald Drill',
    description: 'A highly efficient emerald drill.',
    icon: '💚',
    equipmentType: 'drill',
    basePower: 450,
    cooldownMs: 135,
    moveSpeedMult: 1.0,
    specialEffect: 'efficient',
    price: { emerald: 45, diamond: 75 },
    image: 'emerald_drill',
    maxSkillSlots: 3,
  },
  emerald_pickaxe: {
    id: 'emerald_pickaxe',
    name: 'Emerald Pickaxe',
    description: 'An emerald pickaxe combining precision and power.',
    icon: '🍀',
    equipmentType: 'pickaxe',
    basePower: 650,
    cooldownMs: 320,
    moveSpeedMult: 1.0,
    price: { emerald: 60, diamond: 75 },
    maxSkillSlots: 3,
  },
  ruby_drill: {
    id: 'ruby_drill',
    name: 'Ruby Drill',
    description: 'Uses hardened ruby for powerful mining.',
    icon: '❤️',
    equipmentType: 'drill',
    basePower: 650,
    cooldownMs: 130,
    moveSpeedMult: 1.0,
    price: { ruby: 45, emerald: 75 },
    maxSkillSlots: 4,
  },
  ruby_pickaxe: {
    id: 'ruby_pickaxe',
    name: 'Ruby Pickaxe',
    description: 'A ruby pickaxe with fiery destructive power.',
    icon: '🏮',
    equipmentType: 'pickaxe',
    basePower: 900,
    cooldownMs: 300,
    moveSpeedMult: 1.0,
    price: { ruby: 60, emerald: 75 },
    maxSkillSlots: 4,
  },
  sapphire_drill: {
    id: 'sapphire_drill',
    name: 'Sapphire Drill',
    description: 'A precision sapphire drill.',
    icon: '💙',
    equipmentType: 'drill',
    basePower: 900,
    cooldownMs: 125,
    moveSpeedMult: 1.0,
    price: { sapphire: 45, ruby: 75 },
    maxSkillSlots: 4,
  },
  sapphire_pickaxe: {
    id: 'sapphire_pickaxe',
    name: 'Sapphire Pickaxe',
    description: 'A pickaxe with a cold, razor-sharp sapphire blade.',
    icon: '🧿',
    equipmentType: 'pickaxe',
    basePower: 1200,
    cooldownMs: 280,
    moveSpeedMult: 1.0,
    price: { sapphire: 60, ruby: 75 },
    maxSkillSlots: 4,
  },
  uranium_drill: {
    id: 'uranium_drill',
    name: 'Uranium Drill',
    description: 'Possesses unstable power that triggers micro-explosions.',
    icon: '☢️',
    equipmentType: 'drill',
    basePower: 1300,
    cooldownMs: 120,
    moveSpeedMult: 1.0,
    specialEffect: 'explosive',
    price: { uranium: 45, sapphire: 75 },
    maxSkillSlots: 5,
  },
  uranium_pickaxe: {
    id: 'uranium_pickaxe',
    name: 'Uranium Pickaxe',
    description: 'A fearsome pickaxe that uses radioactive energy in direct impacts.',
    icon: '☣️',
    equipmentType: 'pickaxe',
    basePower: 1800,
    cooldownMs: 260,
    moveSpeedMult: 1.0,
    price: { uranium: 60, sapphire: 75 },
    maxSkillSlots: 5,
  },
  obsidian_drill: {
    id: 'obsidian_drill',
    name: 'Obsidian Drill',
    description: 'The ultimate drill using abyss-grade materials.',
    icon: '🖤',
    equipmentType: 'drill',
    basePower: 1800,
    cooldownMs: 110,
    moveSpeedMult: 1.0,
    price: { obsidian: 45, uranium: 75 },
    maxSkillSlots: 6,
  },
  obsidian_pickaxe: {
    id: 'obsidian_pickaxe',
    name: 'Obsidian Pickaxe',
    description: 'A mythical pickaxe with the hardness of the abyss.',
    icon: '🌑',
    equipmentType: 'pickaxe',
    basePower: 3000,
    cooldownMs: 240,
    moveSpeedMult: 1.0,
    price: { obsidian: 60, uranium: 75 },
    maxSkillSlots: 6,
  },
};

export const getDrillData = (id: string): Drill | undefined => {
  return DRILLS[id];
};
