import { TileType } from '../types/game';
import { AtlasIconName } from './atlasMap';

export interface MineralDefinition {
  key: TileType;
  name: string;
  nameKo: string;
  icon: string;
  description: string;
  descriptionKo: string;
  color: string;
  minDepth: number;
  basePrice: number;
  baseHealth: number;
  defense: number;
  image?: AtlasIconName | null | any;
  tileImage?: AtlasIconName | null | any;
  _cachedImage?: any;
  _cachedTileImage?: any;
}

export const MINERALS: MineralDefinition[] = [
  {
    key: 'crimsonstone',
    name: 'Crimsonstone',
    nameKo: '핏빛석',
    icon: '💎',
    description: 'Mineral from Circle 2 - Lust',
    descriptionKo: '제2원 색욕의 층에서 발견되는 핏빛 광물입니다.',
    color: '#ef4444',
    minDepth: 10,
    basePrice: 5,
    baseHealth: 100,
    defense: 20,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'galestone',
    name: 'Galestone',
    nameKo: '돌풍석',
    icon: '💎',
    description: 'Mineral from Circle 2 - Lust',
    descriptionKo: '강한 바람의 기운이 깃든 광물입니다.',
    color: '#94a3b8',
    minDepth: 110,
    basePrice: 10,
    baseHealth: 200,
    defense: 25,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'fervorstone',
    name: 'Fervorstone',
    nameKo: '열정석',
    icon: '💎',
    description: 'Mineral from Circle 2 - Lust',
    descriptionKo: '뜨거운 열망이 느껴지는 단단한 광물입니다.',
    color: '#f87171',
    minDepth: 210,
    basePrice: 15,
    baseHealth: 300,
    defense: 30,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'moldstone',
    name: 'Moldstone',
    nameKo: '곰팡석',
    icon: '💎',
    description: 'Mineral from Circle 3 - Gluttony',
    descriptionKo: '제3원 탐식의 층에서 발견되는 부패한 광물입니다.',
    color: '#84cc16',
    minDepth: 310,
    basePrice: 10,
    baseHealth: 200,
    defense: 30,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'siltstone',
    name: 'Siltstone',
    nameKo: '침전석',
    icon: '💎',
    description: 'Mineral from Circle 3 - Gluttony',
    descriptionKo: '진흙과 오물이 섞여 굳어진 광물입니다.',
    color: '#71717a',
    minDepth: 410,
    basePrice: 20,
    baseHealth: 400,
    defense: 35,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'gorestone',
    name: 'Gorestone',
    nameKo: '선혈석',
    icon: '💎',
    description: 'Mineral from Circle 3 - Gluttony',
    descriptionKo: '기괴한 붉은 색을 띠는 불결한 광물입니다.',
    color: '#dc2626',
    minDepth: 510,
    basePrice: 30,
    baseHealth: 600,
    defense: 40,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'goldstone',
    name: 'Goldstone',
    nameKo: '사금석',
    icon: '💎',
    description: 'Mineral from Circle 4 - Greed',
    descriptionKo: '제4원 탐욕의 층에서 발견되는 빛나는 광물입니다.',
    color: '#fbbf24',
    minDepth: 610,
    basePrice: 20,
    baseHealth: 400,
    defense: 40,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'luststone',
    name: 'Luststone',
    nameKo: '욕망석',
    icon: '💎',
    description: 'Mineral from Circle 4 - Greed',
    descriptionKo: '보는 이의 소유욕을 자극하는 아름다운 광물입니다.',
    color: '#f472b6',
    minDepth: 710,
    basePrice: 40,
    baseHealth: 800,
    defense: 45,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'midasite',
    name: 'Midasite',
    nameKo: '미다스석',
    icon: '💎',
    description: 'Mineral from Circle 4 - Greed',
    descriptionKo: '닿는 모든 것을 황금으로 바꿀 듯한 광채를 냅니다.',
    color: '#fcd34d',
    minDepth: 810,
    basePrice: 60,
    baseHealth: 1200,
    defense: 50,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'ragestone',
    name: 'Ragestone',
    nameKo: '분노석',
    icon: '💎',
    description: 'Mineral from Circle 5 - Wrath',
    descriptionKo: '제5원 분노의 층에서 발견되는 뜨거운 광물입니다.',
    color: '#ef4444',
    minDepth: 910,
    basePrice: 40,
    baseHealth: 800,
    defense: 50,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'cinderstone',
    name: 'Cinderstone',
    nameKo: '잿빛석',
    icon: '💎',
    description: 'Mineral from Circle 5 - Wrath',
    descriptionKo: '타버린 재가 뭉쳐진 듯한 거친 광물입니다.',
    color: '#52525b',
    minDepth: 1010,
    basePrice: 80,
    baseHealth: 1600,
    defense: 55,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'furystone',
    name: 'Furystone',
    nameKo: '격노석',
    icon: '💎',
    description: 'Mineral from Circle 5 - Wrath',
    descriptionKo: '폭발적인 에너지를 머금고 있는 광물입니다.',
    color: '#b91c1c',
    minDepth: 1110,
    basePrice: 120,
    baseHealth: 2400,
    defense: 60,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'ashstone',
    name: 'Ashstone',
    nameKo: '낙진석',
    icon: '💎',
    description: 'Mineral from Circle 6 - Heresy',
    descriptionKo: '제6원 이단의 층에서 발견되는 메마른 광물입니다.',
    color: '#3f3f46',
    minDepth: 1210,
    basePrice: 80,
    baseHealth: 1600,
    defense: 60,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'blightstone',
    name: 'Blightstone',
    nameKo: '저주석',
    icon: '💎',
    description: 'Mineral from Circle 6 - Heresy',
    descriptionKo: '불길한 원한이 느껴지는 어두운 광물입니다.',
    color: '#4c1d95',
    minDepth: 1310,
    basePrice: 160,
    baseHealth: 3200,
    defense: 65,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'vexite',
    name: 'Vexite',
    nameKo: '고뇌석',
    icon: '💎',
    description: 'Mineral from Circle 6 - Heresy',
    descriptionKo: '파낼수록 알 수 없는 고통이 전해지는 광물입니다.',
    color: '#1e1b4b',
    minDepth: 1410,
    basePrice: 240,
    baseHealth: 4800,
    defense: 70,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'thornstone',
    name: 'Thornstone',
    nameKo: '가시석',
    icon: '💎',
    description: 'Mineral from Circle 7 - Violence',
    descriptionKo: '제7원 폭력의 층에서 발견되는 날카로운 광물입니다.',
    color: '#44403c',
    minDepth: 1510,
    basePrice: 160,
    baseHealth: 3200,
    defense: 70,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'bloodstone',
    name: 'Bloodstone',
    nameKo: '혈석',
    icon: '💎',
    description: 'Mineral from Circle 7 - Violence',
    descriptionKo: '피가 응고된 듯한 짙은 붉은색의 광물입니다.',
    color: '#7f1d1d',
    minDepth: 1610,
    basePrice: 320,
    baseHealth: 6400,
    defense: 75,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'cruelite',
    name: 'Cruelite',
    nameKo: '잔혹석',
    icon: '💎',
    description: 'Mineral from Circle 7 - Violence',
    descriptionKo: '차갑고 무자비한 기운을 내뿜는 단단한 광물입니다.',
    color: '#450a0a',
    minDepth: 1710,
    basePrice: 480,
    baseHealth: 9600,
    defense: 80,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'mimicite',
    name: 'Mimicite',
    nameKo: '의태석',
    icon: '💎',
    description: 'Mineral from Circle 8 - Fraud',
    descriptionKo: '제8원 사기의 층에서 발견되는 기만적인 광물입니다.',
    color: '#164e63',
    minDepth: 1810,
    basePrice: 320,
    baseHealth: 6400,
    defense: 80,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'lurerstone',
    name: 'Lurerstone',
    nameKo: '기만석',
    icon: '💎',
    description: 'Mineral from Circle 8 - Fraud',
    descriptionKo: '환각을 일으켜 탐험가를 유혹하는 광물입니다.',
    color: '#0e7490',
    minDepth: 1910,
    basePrice: 640,
    baseHealth: 12800,
    defense: 85,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'phantomite',
    name: 'Phantomite',
    nameKo: '망령석',
    icon: '💎',
    description: 'Mineral from Circle 8 - Fraud',
    descriptionKo: '실체가 없는 듯 흐릿하게 빛나는 신비한 광물입니다.',
    color: '#155e75',
    minDepth: 2010,
    basePrice: 960,
    baseHealth: 19200,
    defense: 90,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'froststone',
    name: 'Froststone',
    nameKo: '서리석',
    icon: '💎',
    description: 'Mineral from Circle 9 - Treachery',
    descriptionKo: '제9원 배신의 층에서 발견되는 얼어붙은 광물입니다.',
    color: '#bfdbfe',
    minDepth: 2110,
    basePrice: 640,
    baseHealth: 12800,
    defense: 90,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'glacialite',
    name: 'Glacialite',
    nameKo: '빙하석',
    icon: '💎',
    description: 'Mineral from Circle 9 - Treachery',
    descriptionKo: '수만 년간의 냉기를 품고 있는 전설적인 광물입니다.',
    color: '#60a5fa',
    minDepth: 2210,
    basePrice: 1280,
    baseHealth: 25600,
    defense: 95,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'abyssstone',
    name: 'Abyssstone',
    nameKo: '심연석',
    icon: '💎',
    description: 'Mineral from Circle 9 - Treachery',
    descriptionKo: '지옥의 가장 깊은 곳, 절대적인 어둠을 상징하는 광물입니다.',
    color: '#1e3a8a',
    minDepth: 2310,
    basePrice: 1920,
    baseHealth: 38400,
    defense: 100,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
];
