import { TileType, Rarity } from '../types/game';
import { AtlasIconName } from './atlasMap';

export interface MineralDefinition {
  key: TileType;
  name: string;
  icon: string;
  description: string;
  color: string;
  minDepth: number;
  basePrice: number; // 상점 판매 가격 (G)
  baseHealth: number; // 광물 파괴에 필요한 타격 체력
  defense: number; // 광물 방어력
  image?: AtlasIconName | null | any; // 아이템 아이콘 (아틀라스 키)
  tileImage?: AtlasIconName | null | any; // 맵 타일용 (아틀라스 키)
  _cachedImage?: any; // 렌더링 캔버스 최적화용 캐시 객체
  _cachedTileImage?: any; // 타일 렌더링 최적화용 캐시 객체
}

export const MINERALS: MineralDefinition[] = [
  {
    key: 'dirt',
    name: 'Dirt',
    icon: '🟤',
    description: 'The most common surface soil. Has minimal value.',
    color: '#94a3b8',
    minDepth: 0,
    basePrice: 1,
    baseHealth: 30,
    defense: 0,
    image: 'dirt_icon',
    tileImage: 'dirt_tile',
  },
  {
    key: 'stone',
    name: 'Stone',
    icon: '🪨',
    description: 'Hardened rock. Used as basic construction material.',
    color: '#94a3b8',
    minDepth: 0,
    basePrice: 1,
    baseHealth: 100,
    defense: 10,
    image: 'stone_icon',
    tileImage: 'stone_tile',
  },
  {
    key: 'coal',
    name: 'Coal',
    icon: '⬛',
    description: 'Carbon-rich mineral. Useful as fuel or early funding source.',
    color: '#4ade80',
    minDepth: 20,
    basePrice: 5,
    baseHealth: 250,
    defense: 25,
    image: 'coal_icon',
    tileImage: 'coal_tile',
  },
  {
    key: 'iron',
    name: 'Iron',
    icon: '🥈',
    description: 'Dense industrial metal. Serves as the base for various equipment.',
    color: '#4ade80',
    minDepth: 100,
    basePrice: 20,
    baseHealth: 600,
    defense: 60,
    image: 'iron_icon',
    tileImage: 'iron_tile',
  },
  {
    key: 'gold',
    name: 'Gold',
    icon: '🟡',
    description: 'Highly conductive precious metal. Traded at high prices in the shop.',
    color: '#60a5fa',
    minDepth: 300,
    basePrice: 100,
    baseHealth: 600,
    defense: 100,
    image: 'gold_icon',
    tileImage: 'gold_tile',
  },
  {
    key: 'diamond',
    name: 'Diamond',
    icon: '💎',
    description: 'Pure carbon crystals. Extremely hard and disperses light in multiple directions.',
    color: '#ec4899',
    minDepth: 450,
    basePrice: 300,
    baseHealth: 1000,
    defense: 150,
    image: 'diamond_icon',
    tileImage: 'diamond_tile',
  },
  {
    key: 'emerald',
    name: 'Emerald',
    icon: '🟩',
    description: 'Transparent green gem used in precision optical equipment.',
    color: '#a855f7',
    minDepth: 650,
    basePrice: 800,
    baseHealth: 1500,
    defense: 200,
    image: 'emerald_icon',
    tileImage: 'emerald_tile',
  },
  {
    key: 'ruby',
    name: 'Ruby',
    icon: '🟥',
    description: 'Heat-resistant red gem. Used in laser equipment and more.',
    color: '#a855f7',
    minDepth: 850,
    basePrice: 1500,
    baseHealth: 2000,
    defense: 300,
    image: 'ruby_icon',
    tileImage: 'ruby_tile',
  },
  {
    key: 'sapphire',
    name: 'Sapphire',
    icon: '🟦',
    description: 'Extremely hard blue gem. Emits a brilliant light and is the core of high-performance sensor arrays.',
    color: '#ec4899',
    minDepth: 1050,
    basePrice: 3000,
    baseHealth: 3000,
    defense: 450,
    image: null,
    tileImage: 'sapphire_tile',
  },
  {
    key: 'uranium',
    name: 'Uranium',
    icon: '☢️',
    description: 'Unstable but high-energy radioactive element.',
    color: '#f59e0b',
    minDepth: 1200,
    basePrice: 5000,
    baseHealth: 6000,
    defense: 850,
    image: null,
    tileImage: 'uranium_tile',
  },
  {
    key: 'obsidian',
    name: 'Obsidian',
    icon: '🌑',
    description: 'Volcanic glass with atomic-level sharpness. Carries mythical legends.',
    color: '#ef4444',
    minDepth: 1350,
    basePrice: 10000,
    baseHealth: 10000,
    defense: 1200,
    image: null,
    tileImage: 'obsidian_tile',
  },
  {
    key: 'iron_ingot',
    name: 'Iron Ingot',
    icon: '🪚',
    description: 'Smelted iron bar. Essential for advanced crafting.',
    color: '#94a3b8',
    minDepth: -1,
    basePrice: 150,
    baseHealth: 0,
    defense: 0,
    image: 'iron_icon',
  },
  {
    key: 'gold_ingot',
    name: 'Gold Ingot',
    icon: '🏅',
    description: 'Refined gold bar. Very valuable and conductive.',
    color: '#fbbf24',
    minDepth: -1,
    basePrice: 500,
    baseHealth: 0,
    defense: 0,
    image: 'gold_icon',
  },
  {
    key: 'polished_diamond',
    name: 'Polished Diamond',
    icon: '💠',
    description: 'Perfectly cut diamond. Focuses intense energy.',
    color: '#ec4899',
    minDepth: -1,
    basePrice: 8000,
    baseHealth: 0,
    defense: 0,
    image: 'diamond_icon',
  },
  // 특수 타일 데이터 (아틀라스 키값 기반)
  {
    key: 'wall' as any,
    name: 'Wall',
    icon: '🧱',
    description: 'Unbreakable border wall.',
    color: '#1a1a1b',
    minDepth: -2,
    basePrice: 0,
    baseHealth: 1000,
    defense: 0,
    tileImage: 'wall_tile',
  },
  {
    key: 'lava' as any,
    name: 'Lava',
    icon: '🔥',
    description: 'Dangerous liquid fire.',
    color: '#f97316',
    minDepth: -2,
    basePrice: 0,
    baseHealth: Infinity,
    defense: 0,
    tileImage: 'lava_tile',
  },
  {
    key: 'portal' as any,
    name: 'Portal',
    icon: '🌀',
    description: 'Relic of an ancient civilization.',
    color: '#a855f7',
    minDepth: -2,
    basePrice: 0,
    baseHealth: Infinity,
    defense: 0,
    tileImage: 'portal_tile',
  },
  {
    key: 'dungeon_bricks' as any,
    name: 'Dungeon Bricks',
    icon: '🧱',
    description: 'Ancient bricks.',
    color: '#374151',
    minDepth: -2,
    basePrice: 0,
    baseHealth: 1000,
    defense: 0,
    tileImage: 'dungeon_bricks_tile',
  },
  {
    key: 'monster_nest' as any,
    name: 'Monster Nest',
    icon: '🥚',
    description: 'A nest of monsters.',
    color: '#b91c1c',
    minDepth: -2,
    basePrice: 0,
    baseHealth: 200,
    defense: 0,
    tileImage: 'dungeon_bricks_tile', // Fallback
  },
  {
    key: 'boss_core' as any,
    name: 'Boss Core',
    icon: '🟣',
    description: 'The core of a boss.',
    color: '#064e3b',
    minDepth: -2,
    basePrice: 0,
    baseHealth: 10000,
    defense: 0,
    tileImage: 'lava_tile', // Fallback
  },
  {
    key: 'boss_skin' as any,
    name: 'Boss Skin',
    icon: '🟢',
    description: 'The skin of a boss.',
    color: '#064e3b',
    minDepth: -2,
    basePrice: 0,
    baseHealth: 40000,
    defense: 0,
    tileImage: 'lava_tile', // Fallback
  }
];

export const RARITY_COLORS: { [key in Rarity]: string } = {
  Common: '#94a3b8',
  Uncommon: '#4ade80',
  Rare: '#60a5fa',
  Epic: '#a855f7',
  Radiant: '#ec4899',
  Legendary: '#f59e0b',
  Mythic: '#ef4444',
  Ancient: '#22d3ee',
};
